---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - get
  - update
- apiGroups:
  - migration.k8s.io
  resources:
  - storagestates
  - storageversionmigrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migration.k8s.io
  resources:
  - storagestates/status
  - storageversionmigrations/status
  verbs:
  - get
